import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/app/_components/Card";
import { Ticket, AlertTriangle } from "lucide-react";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: 'About - ExitFlight Ticket Generator',
};

const About = () => {

  return (
    <div className="container mx-auto px-4 py-8 md:py-12">
      <div className="max-w-3xl mx-auto">
        <Card className="border-border bg-card">
          <CardHeader>
            <div className="flex items-center mb-4">
              <Ticket className="h-10 w-10 text-primary mr-3" />
              <CardTitle className="text-2xl md:text-3xl font-bold text-foreground">
                About ExitFlight Ticket Generator
              </CardTitle>
            </div>
            <CardDescription className="text-muted-foreground">
              Understanding the purpose of this tool.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-6 text-foreground">
            <section>
              <h2 className="text-xl font-semibold mb-2">What is This Site?</h2>
              <p className="text-muted-foreground leading-relaxed">
                Welcome to ExitFlight! This website is a specialized tool designed to
                generate **mock flight tickets**. The tickets created here are
                for illustrative, presentational, or novelty purposes only.
              </p>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-2">Important Disclaimer</h2>
              <div className="flex items-start p-4 rounded-md bg-destructive/10 text-destructive border border-destructive/30">
                <AlertTriangle className="h-5 w-5 mr-3 mt-1 flex-shrink-0" />
                <div>
                  <h3 className="font-semibold">Not Real Tickets!</h3>
                  <p className="text-sm leading-relaxed">
                    Please be aware that any flight ticket generated by this website is
                    **entirely fictional and cannot be used for actual travel**.
                    Attempting to use these mock tickets for any real-world flight
                    or official purpose is not advised and will not be successful.
                  </p>
                </div>
              </div>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-2">Purpose of the Generator</h2>
              <ul className="list-disc list-inside space-y-1 text-muted-foreground leading-relaxed">
                <li>Creating realistic-looking tickets for presentations or design mockups.</li>
                <li>Generating novelty items for events or personal use.</li>
                <li>Educational purposes to understand the layout of a flight ticket.</li>
                <li>A fun tool for creative projects.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-xl font-semibold mb-2">How It Works</h2>
              <p className="text-muted-foreground leading-relaxed">
                You can select various flight parameters such as departure and
                destination airports, dates, times, airlines, and cabin classes.
                The system then uses this information to generate a visual representation
                of a flight ticket. All flight data, including flight numbers and
                durations, are simulated.
              </p>
            </section>

            <section>
              <p className="text-sm text-center text-muted-foreground italic pt-4">
                Enjoy using the ExitFlight Ticket Generator responsibly!
              </p>
            </section>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};

export default About;
